### ISSUE TITLE
Regarding to global variable in TS

### ISSUE THREAD

**Issue by parkjaeman** [jeremyfa/node-ts2hx#1]
Hi, Jeremy.
I looked around and exercised your great work. And I have a question about current ts2hx.
I don't know if here is proper place to ask some question to you.
My question is about the global variable in typescript.
In case where global variable exists in typescript, I found error on transpiling to haxe.
Is this remaining work in this project?

**Comment by jeremyfa** [comment]
Hi Jaeman,
There are probably many cases that ts2hx doesn't handle yet but please provide an example of typescript file where you are having this issue and I will hopefully be able to update ts2hx to handle it. Thanks for the feedback!

**Comment by parkjaeman** [comment]
Actually, I want to transpile TypeScript file to C++ file like follows.

<< TypeScript: test.ts >>
class Foo_class {
    public prop2:number = 0;
    public foo() {
        for (var i = 0, len = 12; i < len; i++) {
            console.log("for iteration #"+i);
        }

```
}

constructor(public init:number) {
    this.prop2 = init;
}
```

}

class ExecutableFileName {
    static main():void {
        var sample_instance = new Foo_class(5);
        sample_instance.foo();
        console.log("end");
    }
} 

cmd: sudo ts2hx test.ts > ExecutableFileName.hx

<< Haxe: ExecutableFileName.hx >>
package;

class Foo_class {

```
public var prop2:Float = 0;

public function foo() {
    var i:Int = 0, len:Int = 12;
    while (i < len) {
        trace("for iteration #" + i);
        i++;
    }
}

public var init:Float;

public function new(init:Float) {
    this.init = init;
    this.prop2 = init;
}
```

}

class ExecutableFileName {

```
static public function main():Void {
    var sample_instance = new Foo_class(5);
    sample_instance.foo();
    trace("end");
}
```

}

cmd: haxe -main ExecutableFileName.hx -cpp Test

In above example, I could get proper cpp files and executable file with name ExecutableFileName.
However, when I added global variable to test.ts like follows, I failed to compile hax file to cpp file.

<< TypeScript: test.ts >>
var tmp:number = 1;

class Foo_class {
    public prop2:number = 0;
    public foo() {
        console.log(tmp);
        for (var i = 0, len = 12; i < len; i++) {
            console.log("for iteration #"+i);
        }

```
}

constructor(public init:number) {
    this.prop2 = init;
}
```

}

class ExecutableFileName {
    static main():void {
        var sample_instance = new Foo_class(5);
        sample_instance.foo();
        console.log("end");
    }
} 

cmd: sudo ts2hx test.ts > ExecutableFileName.hx

<< Haxe: ExecutableFileName.hx >>
package;

var tmp:Float = 1;
class Foo_class {

```
public var prop2:Float = 0;

public function foo() {
    trace(tmp);
    var i:Int = 0, len:Int = 12;
    while (i < len) {
        trace("for iteration #" + i);
        i++;
    }
}

public var init:Float;

public function new(init:Float) {
    this.init = init;
    this.prop2 = init;
}
```

}

class ExecutableFileName {

```
static public function main():Void {
    var sample_instance = new Foo_class(5);
    sample_instance.foo();
    trace("end");
}
```

}

cmd: haxe -main ExecutableFileName.hx -cpp Test
error_msg: ExecutableFileName.hx:3: characters 0-3 : Unexpected var

As I know, Hax does not support global variable but ts2hx changes "var tmp:number = 1;" to TypeScript syntax like "var tmp:Float = 1;".
I guess this is problem.
How do you think?
I am a starter of TypeScript and Haxe so that it is possible that I don't know basic knowledge on TypeScript and Hax.

**Comment by jeremyfa** [comment]
I see. Ts2hx doesn't perform any check to say if the transpiled haxe code is valid or not because the haxe compiler itself can do this job. Global variable don't exist in Haxe and I don't plan to work on transpiling Typescript global variable into "something that works in Haxe".

However, you are likely to be able to do what you want by using a static property inside a class instead of using a global variable. Basically, because Haxe projects are mainly structured using classes, it is recommended to use classes in Typescript as well.

**Comment by parkjaeman** [comment]
Thank you, Jeremyfa.
I will try to use static property as your commentl..: )
