### ISSUE TITLE
Ts2Hx.JSON*

### ISSUE THREAD

**Issue by elsassph** [jeremyfa/node-ts2hx#5]
Haxe has `haxe.Json.parse()` and `haxe.Json.stringify()` which map to the native browser JSON class or to a custom implementation for other targets.

Optionally you can compile with `-D haxeJSON` to include a JSON fallback for browsers which do not have it built-in.

**Comment by elsassph** [comment]
Should probably look at the support class before commenting...

**Comment by nadako** [comment]
ts2hx could convert integer argument for `space` to a number of spaces :-P
